language: java
jdk: oraclejdk8
sudo: false

script: "mvn cobertura:cobertua"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
	

