language: java
jdk: oraclejdk8
sudo: false
install: true
script: ./mvnw clean install

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
